RecommandationApp/Controllers/AdminController.cs
using RecommandationApp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace RecommandationApp.Controllers
{
    public class AdminController : Controller
    {
        private UtilisateurDBContext db = new UtilisateurDBContext();

        // GET: Admin
        public ActionResult Index(string searchString)
        {
            var utilisateurs = from m in db.Utilisateurs
                select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                utilisateurs = utilisateurs.Where(s => s.nom.Contains(searchString));
            }

            return View(utilisateurs);
        }

        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Utilisateur utilisateur = db.Utilisateurs.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }

            return View(utilisateur);
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,nom,prenom,dateNaissance")]
            Utilisateur utilisateur)
        {
            if (ModelState.IsValid)
            {
                db.Utilisateurs.Add(utilisateur);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(utilisateur);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Utilisateur utilisateur = db.Utilisateurs.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }

            return View(utilisateur);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,nom,prenom,dateNaissance")]
            Utilisateur utilisateur)
        {
            if (ModelState.IsValid)
            {
                db.Entry(utilisateur).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(utilisateur);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Utilisateur utilisateur = db.Utilisateurs.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }

            return View(utilisateur);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utilisateur utilisateur = db.Utilisateurs.Find(id);
            db.Utilisateurs.Remove(utilisateur);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

RecommandationApp/Controllers/OffresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using RecommandationApp.Models;

namespace RecommandationApp.Controllers
{
    public class OffresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Offres
        public ActionResult Index(string offreCat, string searchString)
        {
            var CatLst = new List<string>();

            var CatQry = from d in db.CategoryMs
                orderby d.Category
                select d.Category;

            CatLst.AddRange(CatQry);

            ViewBag.offreCat = new SelectList(CatLst);

            var offres = db.Offres.Include(o => o.Representant);
            
            if (!String.IsNullOrEmpty(searchString))
            {
                offres = offres.Where(s => s.Title.Contains(searchString));
            }
            if (!string.IsNullOrEmpty(offreCat))
            {
                offres = offres.Where(x => x.CategoryM.Category == offreCat);
            }



            return View(offres.ToList());
        }

        // GET: Offres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
//            Include(c => c.Offre).Where();
            var comments = db.Comments.Include(c => c.Client).Where(c => c.Offre == id).ToList();       
            
            
            Offre offre = db.Offres.Find(id);
            var ratings = db.Ratings.Include(r => r.Offre).Where(r => r.Offre.Id == id).ToList();

            offre.Comments = comments;
            offre.Ratings = ratings;
//            offre.Comments = new List<Comment>();
            OffreViewModel offreViewModel = new OffreViewModel();
            offreViewModel.Offre = offre;
            offreViewModel.Comment = new Comment();
            

            if (offre == null)
            {
                return HttpNotFound();
            }

            return View(offreViewModel);
        }

        // GET: Offres/Create
        public ActionResult Create()
        {
            Offre e = new Offre();
            e.image = new byte[7000];
            ViewBag.IdRepresentant = new SelectList(db.Representants, "Id", "nom");
            var CatLst = new List<string>();
            var CatQry = from d in db.CategoryMs
                orderby d.Category
                select d.Category;
            CatLst.AddRange(CatQry);
            ViewBag.offreCat = new SelectList(CatLst);
            return View();
        }

        // POST: Offres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //        public ActionResult Create([Bind(Include = "Id,Title,Description,AdresseRecomo,TelRecomo,Image1,Image2,IdRepresentant")] Offre offre)
        public ActionResult Create(Offre offre)
        {
            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];
                    

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        //                        System.IO.Directory.CreateDirectory("~/Images/");
                        var path = Path.Combine(Server.MapPath("~/images/"), fileName);
                        offre.Image1 = fileName;
                        file.SaveAs(path);
                        using (var binaryReader = new BinaryReader(Request.Files[0].InputStream))
                        {
                            
                            offre.image = binaryReader.ReadBytes(Request.Files[0].ContentLength);
                        }

                    }
                    offre.IdRepresentant = User.Identity.GetUserId();
                    offre.IdCategoryM = 1;
                    db.Offres.Add(offre);
                        db.SaveChanges();
                        return RedirectToAction("Index");                    
                }
            } 
                ViewBag.IdRepresentant = new SelectList(db.Representants, "Id", "nom", offre.IdRepresentant);
                return View(offre);
            
        }
         
            // GET: Offres/Edit/5
            public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offre offre = db.Offres.Find(id);
            if (offre == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdRepresentant = new SelectList(db.Representants, "Id", "nom", offre.IdRepresentant);
            return View(offre);
        }

        // POST: Offres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,AdresseRecomo,TelRecomo,Image1,Image2,IdRepresentant")] Offre offre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(offre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdRepresentant = new SelectList(db.Representants, "Id", "nom", offre.IdRepresentant);
            return View(offre);
        }

        // GET: Offres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offre offre = db.Offres.Find(id);
            if (offre == null)
            {
                return HttpNotFound();
            }
            return View(offre);
        }

        // POST: Offres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Offre offre = db.Offres.Find(id);
            db.Offres.Remove(offre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        //        public ActionResult Create([Bind(Include = "Id,Title,Description,AdresseRecomo,TelRecomo,Image1,Image2,IdRepresentant")] Offre offre)
        public ActionResult CreateComment(OffreViewModel offer)
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            //            comment.Comment.User = currentUser.Client;
            //            comment.Offre = 
            Comment com = new Comment();
            com.Client = currentUser.Client;
            com.Text = offer.Comment.Text;
            com.Offre = offer.Offre.Id;
            db.Comments.Add(com);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Rate(int? id, double rating)
        {
            /*
            var Users = db.Clients.ToList();
            var Offers = db.Offres.ToList();
//            string[] images = new string[] { "i1.jpg", "restaurant.jpg", "camp.jpg", "caf.jpg", "library.jpg1" };
            int k = 0;
            foreach (var user in Users)
            {
                if (k == 83) break;
                foreach(var of in Offers)
                {
                    Random rd = new Random();
                    int rInt = rd.Next(0, 3); //for ints
                    Rating rt = new Rating();
                    rt.value = rInt;
                    rt.Offre = of;
                    rt.Client = user;
                    db.Ratings.Add(rt);
                    db.SaveChanges();
                }
                k++;       
            }
            */
            Rating r = new Rating();
            r.value = rating;
            var offer = db.Offres.Find(id);                        
            int? idv = id;
            var ratings = db.Ratings.Include(rt => rt.Offre).Where(rt => rt.Offre.Id == id).ToList();
            offer.Ratings = ratings;
            offer.Ratings.Add(r);
            db.Entry(offer).State = EntityState.Modified;
            db.SaveChanges();
            //            return Content("rating offre id: " + offer.Title+ " is "+rating);
            return RedirectToAction("Details", new { id = idv });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RecommandationApp/Controllers/RepresentantController.cs
using RecommandationApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;

namespace RecommandationApp.Controllers
{
    public class RepresentantController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Representant
        public ActionResult Index(string searchString)
        {
            var representants = from m in db.Representants
                               select m;
            if (!String.IsNullOrEmpty(searchString))
            {
                representants = representants.Where(s => s.entreprise.Contains(searchString));
            }

            return View(representants);
        }

        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Representant representant = db.Representants.Find(id);
            if (representant == null)
            {
                return HttpNotFound();
            }
            return View(representant);
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,nom, prenom, entreprise,adresse")] Representant representant )
        {
            if (ModelState.IsValid)
            {
                db.Representants.Add(representant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(representant);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Representant representant = db.Representants.Find(id);
            if (representant == null)
            {
                return HttpNotFound();
            }
            return View(representant);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,nom, prenom, entreprise,adresse")] Representant representant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(representant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(representant);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Representant representant = db.Representants.Find(id);
            if (representant == null)
            {
                return HttpNotFound();
            }
            return View(representant);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Representant representant = db.Representants.Find(id);
            db.Representants.Remove(representant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }

}

RecommandationApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Site de Recommandation</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/jquery-ui.css")
    @Styles.Render("~/Content/boostrap/bootstrap.min.css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/magnific-popup/magnific-popup.css")
    @Styles.Render("~/Content/owl-coursel/owl.carousel.css")
    @Styles.Render("~/Content/owl-coursel/owl.theme.css")
    @Styles.Render("~/Content/style.css")
    @Styles.Render("~/Content/light-version.css")
    @Styles.Render("~/Content/padd-mr.css")
    @Scripts.Render("~/bundles/modernizr")


</head>

<body class="bg-3">
    <!-- Preloader -->
    <div class="preloader">
        <p></p>
    </div>
    <div id="wrap" class="color1-inher">
        <!-- Header-->
        <header id="wrap-header" class="color-inher">
            <div class="top-header">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 col-md-6 col-lg-6 hidden-xs">
                            <p class="f-14">
                                <i class="fa fa-map-marker m-r-lg-5"></i><strong>RECOMMANDATION</strong> - RUE 35 NR 10 OULFA CASABLANCA,
                                MAROC
                            </p>
                        </div>
                        <div class="col-sm-6 col-md-6 col-lg-6">
                            @Html.Partial("_LoginPartial")
                        </div>
                    </div>
                </div>
            </div>
            <!-- Menu -->
            <div class="menu-bg">
                <div class="container">
                    <div class="row">
                        <!-- Logo -->
                        <div class="col-md-3 col-lg-3">
                            @Html.ActionLink("App de Recommandation", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                        </div>
                        <div class="col-md-9 col-lg-9">
                            <div class="hotline">
                                <span class="m-r-lg-10">Pour plus de renseignement:</span>
                                <i class="fa fa-phone"></i>+212 663660530
                            </div>
                            <div class="clearfix"></div>
                            <!-- Menu -->
                            <div class="main-menu">
                                <div class="container1">
                                    <nav class="navbar navbar-default menu">
                                        <div class="container1-fluid">
                                            <div class="navbar-header">
                                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                                                        aria-expanded="false">
                                                    <span class="sr-only">Toggle navigation</span>
                                                    <span class="icon-bar"></span>
                                                    <span class="icon-bar"></span>
                                                    <span class="icon-bar"></span>
                                                </button>
                                            </div>
                                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                                <ul class="nav navbar-nav">
                                                    @if (Request.IsAuthenticated)
                                                    {
                                                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                                        if (this.User.IsInRole("RepresentantRole"))
                                                        {

                                                            <li>@Html.ActionLink("AJOUT", "Create", "Offres")</li>
                                                            <li>@Html.ActionLink("OFFRES", "Index", "Offres")</li>
                                                            <li>@Html.ActionLink("PROFIL", "Index", "Offres")</li>

                                                        }
                                                        else if (this.User.IsInRole("ClientRole"))
                                                        {
                                                            <li>@Html.ActionLink("Recherche", "Index", "Offres")</li>
                                                            <li>@Html.ActionLink("Recommandation", "Index", "Recommendation")</li>
                                                            <li>@Html.ActionLink("Profil", "Index", "Profil")</li>
                                                        }
                                                        else
                                                        {
                                                            <li>@Html.ActionLink("Utilisateurs", "Index", "Admin")</li>
                                                            <li>@Html.ActionLink("Representants", "Index", "Representant")</li>
                                                        }
                                                    }
                                                    else
                                                    {
                                                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                                        <li>@Html.ActionLink("About", "About", "Home")</li>
                                                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                                    }
                                                </ul>
                                            </div>
                                        </div>
                                    </nav>
                                    <!-- Search -->
                                    <div class="search-box">
                                        <i class="fa fa-search"></i>
                                        <form>
                                            <input type="text" name="search-txt" placeholder="Rechercher..." class="search-txt form-item">
                                            <button type="submit" name="submit" class="search-btn btn-1">
                                                <i class="fa fa-search"></i>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <div class="container body-content">
            @RenderBody()
            <hr />

            <!-- Footer-->
            <footer id="wrap-footer" class="bg-gray-1 color-inher">
                <!-- Footer top -->
                <div class="footer-top">
                    <div class="container">
                        <div class="bg-gray-1 p-l-r">
                            <div class="row">
                                <!-- Company info -->
                                <div class="col-xs-12 col-sm-4 col-md-4">
                                    <div class="heading-1">
                                        <h3>Information Entreprise</h3>
                                    </div>
                                    <p>
                                        10 ans d'experience dans le domaine de location de Voiture, Moto, Grand Bus avec Chauffeur.
                                    </p>
                                    <ul class="list-default">
                                        <li><i class="fa fa-signal"></i>Rue 35 NR 10 OULFA CASABLANCA - MAROC</li>
                                        <li><i class="fa fa-phone"></i>+212 663660530</li>
                                        <li><i class="fa fa-envelope-o"></i>bensaleh.mehdi@gmail.com</li>
                                        <li><i class="fa fa-globe"></i>http://sysrecommmandation.com</li>
                                    </ul>
                                </div>
                                <!-- Newsletter -->
                                <div class="col-xs-12 col-sm-4 col-md-4">
                                    <div class="newsletter text-left">
                                        <div class="heading-1">
                                            <h3>Inscrivez Vous</h3>
                                        </div>
                                        <p>Si vous voulez faire une réservation d'un de nos véhicule , et vous n'êtes encore pas inscrit </p>
                                        <form>
                                            <div class="form-group">
                                                <input type="email" class="form-control form-item" id="Email1" placeholder="Email">
                                            </div>
                                            <button type="submit" class="ht-btn ht-btn-default">Inscription</button>
                                        </form>
                                    </div>
                                </div>
                                <!-- Quick link -->
                                <div class="col-xs-12 col-sm-4 col-md-4">
                                    <div class="heading-1">
                                        <h3>Lien sur le site</h3>
                                    </div>
                                    <ul class="list-default">
                                        <li><a href="index.php"><i class="fa fa-angle-right"></i>Accueil</a></li>

                                        <li><a href="about.php"><i class="fa fa-angle-right"></i>A propos</a></li>
                                        <li><a href="contact.php"><i class="fa fa-angle-right"></i>Contactez Nous</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Footer bottom -->
                <div class="footer-bt color-inher">
                    <div class="container">
                        <div class="bg-gray-0c p-l-r">
                            <div class="row">
                                <div class="col-md-6">
                                    <p>
                                        © 2018 Designed by <a href="">HATIMY/BANI</a>. Copyright

                                    </p>
                                </div>
                                <div class="col-md-6">
                                    <ul class="social-icon list-inline pull-right">
                                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                        <li><a href="#"><i class="fa fa-google"></i></a></li>
                                        <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>

    </div>
    @Scripts.Render("~/bundles/jquery")    
    @Scripts.Render("~/bundles/rating")

    <!-- jQuery -->
    <script src="~/Scripts/jquery/jquery-2.2.4.min.js"></script>
    <!-- JqueryUI -->
    <script src="~/Scripts/jquery/jquery-ui.js"></script>
    <!-- Bootstrap -->
    <script src="~/Scripts/bootstrap/bootstrap.min.js"></script>
    <!--magnific popup-->
    <script src="~/Scripts/magnific-popup/jquery.magnific-popup.min.js"></script>
    <!-- Jquery.counterup -->
    <script src="~/Scripts/jquery.counterup/waypoints.min.js"></script>
    <script src="~/Scripts/jquery.counterup/jquery.counterup.min.js"></script>
    <!-- Owl-coursel -->
    <script src="~/Scripts/owl-coursel/owl.carousel.js"></script>
    <!-- Script -->
    <script src="~/Scripts/script.js"></script>
    @* @Scripts.Render("~/bundles/rating"); *@
    @RenderSection("scripts", required: false)
</body>
</html>